moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.12.15
project:
  name: calculator-collection
  mode: personal
  description: ''
  created_at: '2026-02-01 11:31:38'
  optimized: false
  template_version: 1.12.15
